spring.application.name=esp32-protocol-lab
esp32.base-url=http://192.168.0.236
esp32.led-path=/led

#Mqtt secrets
mqtt.server=${MQTT_SERVER}
mqtt.port=${MQTT_PORT:1883}
mqtt.user=${MQTT_USER}
mqtt.password=${MQTT_PASSWORD}